spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/foodapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Welcome@2022

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a74c7dfdc5d40a2bb8482d8c39db5c9ec
jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deepaksuresh3105@gmail.com
spring.mail.password=flzbxiiayricqxbu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
